{
 "title": "Aktuelle Temperaturen",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Puffer 1",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT p11 AS \"Unten\", p12 AS \"Mitte 1\", p13 AS \"Mitte 2\", p14 AS \"Oben\" FROM heizung_data LIMIT 50 "
    }
   ]
  },
  {
   "title": "Puffer 2",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT p21 AS \"Unten\", p22 AS \"Mitte 1\", p23 AS \"Mitte 2\", p24 AS \"Oben\" FROM heizung_data LIMIT 50 "
    }
   ]
  },
  {
   "title": "H",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT hk, hv, hr, hu FROM heizung_data LIMIT 50 "
    }
   ]
  },
  {
   "title": "k",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT kv, kr FROM heizung_data LIMIT 50 "
    }
   ]
  },
  {
   "title": "O",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ok, ov, \"or\" FROM heizung_data LIMIT 50 "
    }
   ]
  }
 ]
}