version: "3.8"

services:
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: grafana
      POSTGRES_PASSWORD: grafana
      POSTGRES_DB: grafana
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - grafana-network
    restart: unless-stopped

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - grafana-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
      - ./dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - postgres
    networks:
      - grafana-network
    entrypoint:
      - /bin/sh
      - -c
      - |
        apk --no-cache add postgresql-client && \
        until pg_isready -h postgres -p 5432 -U grafana; do
          echo "Waiting for postgres at postgres:5432";
          sleep 2;
        done;
        /run.sh
    restart: unless-stopped

volumes:
  postgres-data:
  grafana-data:

networks:
  grafana-network:
